import React, { useEffect, useState } from 'react';
import './Dashboard.css';

export default function Dashboard({ workerId, onSignOut }) {
  const [worker, setWorker] = useState(null);
  const workerName = localStorage.getItem('wiseworks_worker_name') || null;

  useEffect(() => {
    const stored = localStorage.getItem('wiseworks_worker');
    if (stored) {
      try { setWorker(JSON.parse(stored)); } catch {}
    }
  }, [workerId]);

  const handleDownloadResume = async () => {
    if (!worker) return;
    const { default: jsPDF } = await import('jspdf');
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pageWidth = pdf.internal.pageSize.getWidth();
    const margin = 20;
    const contentWidth = pageWidth - margin * 2;
    let y = 20;

    const certs = Array.isArray(worker.certifications)
      ? worker.certifications.join(', ')
      : worker.certifications || 'N/A';

    const specs = Array.isArray(worker.specialties)
      ? worker.specialties.join(', ')
      : worker.specialties || 'N/A';

    const displayName = workerName || worker.id?.slice(0, 8) || 'Worker';

    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(22);
    pdf.setTextColor(17, 17, 17);
    pdf.text(displayName, margin, y); y += 8;

    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(12);
    pdf.setTextColor(26, 122, 138);
    pdf.text(worker.trade || 'Skilled Trades', margin, y); y += 6;

    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(9);
    pdf.setTextColor(120, 120, 120);
    pdf.text(`${worker.location || 'Canada'}  |  ${worker.availability || 'Full-time'}`, margin, y); y += 4;

    pdf.setDrawColor(26, 122, 138);
    pdf.setLineWidth(0.8);
    pdf.line(margin, y, pageWidth - margin, y); y += 8;

    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(10);
    pdf.setTextColor(100, 100, 100);
    pdf.text('PROFESSIONAL SUMMARY', margin, y); y += 5;

    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(10);
    pdf.setTextColor(60, 60, 60);
    const summary = worker.profile_summary || `${worker.trade} with ${worker.experience_years} years of experience.`;
    const summaryLines = pdf.splitTextToSize(summary, contentWidth);
    pdf.text(summaryLines, margin, y); y += summaryLines.length * 5 + 6;

    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(10);
    pdf.setTextColor(100, 100, 100);
    pdf.text('EXPERIENCE', margin, y); y += 5;

    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(10);
    pdf.setTextColor(60, 60, 60);
    pdf.text(`${worker.experience_years || 0} years in ${worker.trade || 'Skilled Trades'}`, margin + 2, y); y += 10;

    if (certs && certs !== 'N/A') {
      pdf.setFont('helvetica', 'bold');
      pdf.setFontSize(10);
      pdf.setTextColor(100, 100, 100);
      pdf.text('CERTIFICATIONS', margin, y); y += 5;
      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(10);
      pdf.setTextColor(60, 60, 60);
      const certLines = pdf.splitTextToSize(certs, contentWidth);
      pdf.text(certLines, margin + 2, y); y += certLines.length * 5 + 6;
    }

    if (specs && specs !== 'N/A') {
      pdf.setFont('helvetica', 'bold');
      pdf.setFontSize(10);
      pdf.setTextColor(100, 100, 100);
      pdf.text('SPECIALTIES & SKILLS', margin, y); y += 5;
      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(10);
      pdf.setTextColor(60, 60, 60);
      const specLines = pdf.splitTextToSize(specs, contentWidth);
      pdf.text(specLines, margin + 2, y); y += specLines.length * 5 + 6;
    }

    pdf.setFont('helvetica', 'bold');
    pdf.setFontSize(10);
    pdf.setTextColor(100, 100, 100);
    pdf.text('RATE & AVAILABILITY', margin, y); y += 5;
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(10);
    pdf.setTextColor(60, 60, 60);
    pdf.text(`Expected Rate: $${worker.hourly_rate_expectation || 0}/hr  |  ${worker.availability || 'Full-time'}`, margin + 2, y); y += 10;

    pdf.setFont('helvetica', 'italic');
    pdf.setFontSize(8);
    pdf.setTextColor(180, 180, 180);
    pdf.text('Generated by WiseWorks · wiseworks.ca', pageWidth / 2, y, { align: 'center' });

    pdf.save(`WiseWorks_Resume_${displayName.replace(' ', '_')}.pdf`);
  };

  const initials = workerName
    ? workerName.split(' ').map(n => n[0]).join('').toUpperCase().slice(0, 2)
    : worker?.trade?.slice(0, 2).toUpperCase() || 'WW';

  const certs = worker
    ? (Array.isArray(worker.certifications)
      ? worker.certifications
      : (worker.certifications || '').split(',').map(s => s.trim()).filter(Boolean))
    : [];

  const specs = worker
    ? (Array.isArray(worker.specialties)
      ? worker.specialties
      : (worker.specialties || '').split(',').map(s => s.trim()).filter(Boolean))
    : [];

  return (
    <div className="dashboard-page">
      <div className="dashboard-grid">

        {/* LEFT — Worker Info */}
        <div className="dashboard-left">
          <div className="dashboard-card">

            <div className="dashboard-avatar">
              <span>{initials}</span>
            </div>

            <h2 className="dashboard-worker-name">
              {workerName || `Worker ${worker?.id?.slice(0, 8) || '...'}`}
            </h2>
            <p className="dashboard-trade">{worker?.trade || '—'}</p>

            <div className="dashboard-divider" />

            <div className="dashboard-info-grid">
              <div className="dashboard-info-item">
                <span className="dashboard-info-label">Experience</span>
                <span className="dashboard-info-value">{worker?.experience_years || 0} years</span>
              </div>
              <div className="dashboard-info-item">
                <span className="dashboard-info-label">Location</span>
                <span className="dashboard-info-value">{worker?.location || '—'}</span>
              </div>
              <div className="dashboard-info-item">
                <span className="dashboard-info-label">Availability</span>
                <span className="dashboard-info-value">{worker?.availability || '—'}</span>
              </div>
              <div className="dashboard-info-item">
                <span className="dashboard-info-label">Expected Rate</span>
                <span className="dashboard-info-value">${worker?.hourly_rate_expectation || 0}/hr</span>
              </div>
            </div>

            {certs.length > 0 && (
              <div className="dashboard-tags-section">
                <p className="dashboard-tags-label">Certifications</p>
                <div className="dashboard-tags">
                  {certs.map((c, i) => (
                    <span key={i} className="dashboard-tag dashboard-tag--gold">{c}</span>
                  ))}
                </div>
              </div>
            )}

            {specs.length > 0 && (
              <div className="dashboard-tags-section">
                <p className="dashboard-tags-label">Specialties</p>
                <div className="dashboard-tags">
                  {specs.map((s, i) => (
                    <span key={i} className="dashboard-tag dashboard-tag--teal">{s}</span>
                  ))}
                </div>
              </div>
            )}

            <button className="dashboard-signout-btn" onClick={onSignOut}>
              Sign Out
            </button>

          </div>
        </div>

        {/* RIGHT — Resume */}
        <div className="dashboard-right">
          <div className="dashboard-resume-header">
            <h2 className="dashboard-resume-title">Your Resume</h2>
            <button className="dashboard-download-btn" onClick={handleDownloadResume}>
              ⬇ Download PDF
            </button>
          </div>

          <div className="dashboard-resume-card">

            <div className="resume-preview-top">
              <div className="resume-preview-avatar">{initials}</div>
              <div>
                <h3 className="resume-preview-name">
                  {workerName || `${worker?.trade || 'Skilled'} Professional`}
                </h3>
                <p className="resume-preview-trade">{worker?.trade}</p>
                <p className="resume-preview-location">
                  {worker?.location} · {worker?.availability}
                </p>
              </div>
            </div>

            {worker?.profile_summary && (
              <div className="resume-preview-section">
                <h4 className="resume-preview-section-title">Professional Summary</h4>
                <p className="resume-preview-text">{worker.profile_summary}</p>
              </div>
            )}

            <div className="resume-preview-section">
              <h4 className="resume-preview-section-title">Experience</h4>
              <p className="resume-preview-exp">
                <span className="resume-preview-exp-years">{worker?.experience_years || 0}</span>
                <span className="resume-preview-exp-label"> years in {worker?.trade}</span>
              </p>
            </div>

            {certs.length > 0 && (
              <div className="resume-preview-section">
                <h4 className="resume-preview-section-title">Certifications</h4>
                <div className="resume-preview-tags">
                  {certs.map((c, i) => (
                    <span key={i} className="resume-preview-tag resume-preview-tag--gold">{c}</span>
                  ))}
                </div>
              </div>
            )}

            {specs.length > 0 && (
              <div className="resume-preview-section">
                <h4 className="resume-preview-section-title">Specialties</h4>
                <div className="resume-preview-tags">
                  {specs.map((s, i) => (
                    <span key={i} className="resume-preview-tag resume-preview-tag--teal">{s}</span>
                  ))}
                </div>
              </div>
            )}

            <div className="resume-preview-section">
              <h4 className="resume-preview-section-title">Rate & Availability</h4>
              <div className="resume-preview-rate-grid">
                <div className="resume-preview-rate-card">
                  <span className="resume-preview-rate-value">${worker?.hourly_rate_expectation || 0}/hr</span>
                  <span className="resume-preview-rate-label">Expected Rate</span>
                </div>
                <div className="resume-preview-rate-card">
                  <span className="resume-preview-rate-value">{worker?.availability || 'Full-time'}</span>
                  <span className="resume-preview-rate-label">Availability</span>
                </div>
              </div>
            </div>

            <div className="resume-preview-footer">
              <span>Generated by WiseWorks · wiseworks.ca</span>
            </div>

          </div>
        </div>

      </div>
    </div>
  );
}