'use client'

import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { motion } from 'framer-motion'
import { Download, ArrowLeft, MapPin, Mail, Phone } from 'lucide-react'
import { mockResume } from '@/mock/carlos'
import type { Resume } from '@/types'

export default function ResumePage() {
  const router = useRouter()
  const [resume, setResume] = useState<Resume>(mockResume)
  const [downloading, setDownloading] = useState(false)

  useEffect(() => {
    const stored = localStorage.getItem('wisehire_profile')
    if (stored) {
      const parsed = JSON.parse(stored)
      setResume({
        ...mockResume,
        name: parsed.name || mockResume.name,
        contact: {
          ...mockResume.contact,
          location: parsed.location || mockResume.contact.location,
        },
      })
    }
  }, [])

  const handleDownload = async () => {
    setDownloading(true)
    try {
      const { default: jsPDF } = await import('jspdf')
      const pdf = new jsPDF('p', 'mm', 'a4')
      const pageWidth = pdf.internal.pageSize.getWidth()
      const margin = 20
      const contentWidth = pageWidth - margin * 2
      let y = 20

      pdf.setFont('helvetica', 'bold')
      pdf.setFontSize(22)
      pdf.setTextColor(17, 17, 17)
      pdf.text(resume.name, margin, y)
      y += 8

      pdf.setFont('helvetica', 'bold')
      pdf.setFontSize(12)
      pdf.setTextColor(249, 115, 22)
      pdf.text(mockResume.experience[0].title, margin, y)
      y += 6

      pdf.setFont('helvetica', 'normal')
      pdf.setFontSize(9)
      pdf.setTextColor(120, 120, 120)
      pdf.text(
        `${resume.contact.email}  |  ${resume.contact.phone}  |  ${resume.contact.location}`,
        margin,
        y
      )
      y += 4

      pdf.setDrawColor(249, 115, 22)
      pdf.setLineWidth(0.8)
      pdf.line(margin, y, pageWidth - margin, y)
      y += 8

      pdf.setFont('helvetica', 'bold')
      pdf.setFontSize(10)
      pdf.setTextColor(100, 100, 100)
      pdf.text('PROFESSIONAL SUMMARY', margin, y)
      y += 5

      pdf.setFont('helvetica', 'normal')
      pdf.setFontSize(10)
      pdf.setTextColor(60, 60, 60)
      const summaryLines = pdf.splitTextToSize(resume.summary, contentWidth)
      pdf.text(summaryLines, margin, y)
      y += summaryLines.length * 5 + 6

      pdf.setFont('helvetica', 'bold')
      pdf.setFontSize(10)
      pdf.setTextColor(100, 100, 100)
      pdf.text('EXPERIENCE', margin, y)
      y += 5

      resume.experience.forEach(exp => {
        pdf.setFont('helvetica', 'bold')
        pdf.setFontSize(11)
        pdf.setTextColor(17, 17, 17)
        pdf.text(exp.title, margin, y)
        pdf.setFont('helvetica', 'normal')
        pdf.setFontSize(9)
        pdf.setTextColor(120, 120, 120)
        pdf.text(exp.duration, pageWidth - margin, y, { align: 'right' })
        y += 5
        pdf.setFont('helvetica', 'bold')
        pdf.setFontSize(10)
        pdf.setTextColor(249, 115, 22)
        pdf.text(exp.company, margin, y)
        y += 5
        exp.bullets.forEach(bullet => {
          pdf.setFont('helvetica', 'normal')
          pdf.setFontSize(10)
          pdf.setTextColor(60, 60, 60)
          const lines = pdf.splitTextToSize(`• ${bullet}`, contentWidth - 4)
          pdf.text(lines, margin + 2, y)
          y += lines.length * 5
        })
        y += 4
      })

      pdf.setFont('helvetica', 'bold')
      pdf.setFontSize(10)
      pdf.setTextColor(100, 100, 100)
      pdf.text('CERTIFICATIONS', margin, y)
      y += 5
      pdf.setFont('helvetica', 'normal')
      pdf.setFontSize(10)
      pdf.setTextColor(60, 60, 60)
      resume.certifications.forEach(cert => {
        pdf.text(`• ${cert}`, margin + 2, y)
        y += 5
      })
      y += 4

      pdf.setFont('helvetica', 'bold')
      pdf.setFontSize(10)
      pdf.setTextColor(100, 100, 100)
      pdf.text('SKILLS', margin, y)
      y += 5
      pdf.setFont('helvetica', 'normal')
      pdf.setFontSize(10)
      pdf.setTextColor(60, 60, 60)
      const skillsText = resume.skills.join('  ·  ')
      const skillLines = pdf.splitTextToSize(skillsText, contentWidth)
      pdf.text(skillLines, margin, y)
      y += skillLines.length * 5 + 8

      pdf.setFont('helvetica', 'italic')
      pdf.setFontSize(8)
      pdf.setTextColor(180, 180, 180)
      pdf.text('Generated by WiseHire · wisehire.ca', pageWidth / 2, y, { align: 'center' })

      pdf.save(`${resume.name.replace(' ', '_')}_Resume.pdf`)
    } catch (err) {
      console.error('PDF error:', err)
    } finally {
      setDownloading(false)
    }
  }

  return (
    <main className="min-h-screen bg-[#0A0A0F] text-white">

      {/* Nav */}
      <nav className="flex items-center justify-between px-8 py-6 border-b border-[#1E1E2E]">
        <span className="font-display text-xl font-bold">
          Wise<span className="text-[#F97316]">Hire</span>
        </span>
        <div className="flex items-center gap-4">
          <button
            onClick={() => router.push('/profile')}
            className="flex items-center gap-2 text-sm text-[#A1A1AA] hover:text-white transition-colors"
          >
            <ArrowLeft size={16} />
            Back to Profile
          </button>
          <button
            onClick={handleDownload}
            disabled={downloading}
            className="flex items-center gap-2 bg-[#F97316] hover:bg-orange-400 disabled:opacity-60 text-white text-sm font-medium px-4 py-2 rounded-lg transition-colors"
          >
            {downloading ? (
              <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
            ) : (
              <Download size={16} />
            )}
            Download PDF
          </button>
        </div>
      </nav>

      {/* Resume preview */}
      <div className="max-w-3xl mx-auto px-6 py-12">
        <motion.div
          initial={{ opacity: 0, y: 24 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, ease: [0.22, 1, 0.36, 1] }}
          className="bg-white text-gray-900 rounded-2xl p-10 shadow-[0_0_80px_rgba(249,115,22,0.08)]"
        >
          {/* Header */}
          <div className="border-b-2 border-orange-500 pb-6 mb-6">
            <h1 className="text-3xl font-bold text-gray-900 mb-1">{resume.name}</h1>
            <p className="text-orange-500 font-semibold text-lg mb-3">
              {mockResume.experience[0].title}
            </p>
            <div className="flex flex-wrap gap-4 text-sm text-gray-500">
              <span className="flex items-center gap-1"><Mail size={13} />{resume.contact.email}</span>
              <span className="flex items-center gap-1"><Phone size={13} />{resume.contact.phone}</span>
              <span className="flex items-center gap-1"><MapPin size={13} />{resume.contact.location}</span>
            </div>
          </div>

          {/* Summary */}
          <div className="mb-6">
            <h2 className="text-xs font-bold text-gray-400 uppercase tracking-widest mb-2">Professional Summary</h2>
            <p className="text-gray-700 text-sm leading-relaxed">{resume.summary}</p>
          </div>

          {/* Experience */}
          <div className="mb-6">
            <h2 className="text-xs font-bold text-gray-400 uppercase tracking-widest mb-4">Experience</h2>
            <div className="space-y-5">
              {resume.experience.map((exp, i) => (
                <div key={i}>
                  <div className="flex items-start justify-between mb-1">
                    <div>
                      <h3 className="font-bold text-gray-900">{exp.title}</h3>
                      <p className="text-orange-500 text-sm font-medium">{exp.company}</p>
                    </div>
                    <span className="text-gray-400 text-sm flex-shrink-0 ml-4">{exp.duration}</span>
                  </div>
                  <ul className="mt-2 space-y-1">
                    {exp.bullets.map((bullet, j) => (
                      <li key={j} className="text-gray-600 text-sm flex items-start gap-2">
                        <span className="text-orange-500 mt-1 flex-shrink-0">•</span>
                        {bullet}
                      </li>
                    ))}
                  </ul>
                </div>
              ))}
            </div>
          </div>

          {/* Certifications */}
          <div className="mb-6">
            <h2 className="text-xs font-bold text-gray-400 uppercase tracking-widest mb-3">Certifications</h2>
            <div className="flex flex-wrap gap-2">
              {resume.certifications.map((cert, i) => (
                <span key={i} className="bg-orange-50 border border-orange-200 text-orange-700 text-xs px-3 py-1 rounded-full">
                  {cert}
                </span>
              ))}
            </div>
          </div>

          {/* Skills */}
          <div>
            <h2 className="text-xs font-bold text-gray-400 uppercase tracking-widest mb-3">Skills</h2>
            <div className="flex flex-wrap gap-2">
              {resume.skills.map((skill, i) => (
                <span key={i} className="bg-gray-100 text-gray-700 text-xs px-3 py-1 rounded-full">
                  {skill}
                </span>
              ))}
            </div>
          </div>

          {/* Footer */}
          <div className="mt-8 pt-4 border-t border-gray-100 text-center">
            <p className="text-gray-300 text-xs">Generated by WiseHire · wisehire.ca</p>
          </div>
        </motion.div>
      </div>
    </main>
  )
}
